# Model List Column configuration
list: ~/plugins/azeyn/galleries/models/collection/columns.yaml

# Model Class name
modelClass: Azeyn\Galleries\Models\Collection

# List Title
title: azeyn.galleries::lang.collections.list_title

# Link URL for each record
recordUrl: azeyn/galleries/collections/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 5

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
